#!/bin/bash
eingabe=$1
ausgabe=$2




cat $eingabe  > index.m3u

	echo "#EXTM3U" > ablage.m3u 
	cat index.m3u | grep -A1 -i ",Das Erste"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_2B5C_41B_A401_FFFF0000_0_0_0.png\" tvg-id=\"DasErste.de\" tvg-name=\"DAS ERSTE HD\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DasErste" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_2B5C_41B_A401_FFFF0000_0_0_0.png\" tvg-id=\"DasErste.de\" tvg-name=\"DAS ERSTE HD\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ARD HD"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_2B5C_41B_A401_FFFF0000_0_0_0.png\" tvg-id=\"DasErste.de\" tvg-name=\"DAS ERSTE HD\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ARD FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_2B5C_41B_A401_FFFF0000_0_0_0.png\" tvg-id=\"DasErste.de\" tvg-name=\"DAS ERSTE HD\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ZDF HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_2B66_437_66_FFFF0000_0_0_0.png\" tvg-id=\"ZDF.de\" tvg-name=\"ZDF HD\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ZDF FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_2B66_437_66_FFFF0000_0_0_0.png\" tvg-id=\"ZDF.de\" tvg-name=\"ZDF HD\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ZDF RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_2B66_437_66_FFFF0000_0_0_0.png\" tvg-id=\"ZDF.de\" tvg-name=\"ZDF HD\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SWR" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_DB2A_231_270F_FFFF0000_0_0_0.png\" tvg-id=\"SWRFernsehen.de\" tvg-name=\"SWR HD\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SRF 1"  |  sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_4331_300C_13E_820000_0_0_0.png\" tvg-id=\"SRF1.ch\" tvg-name=\"SRF 1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SRF1" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_4331_300C_13E_820000_0_0_0.png\" tvg-id=\"SRF1.ch\" tvg-name=\"SRF 1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SRF 2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_4332_300C_13E_820000_0_0_0.png\" tvg-id=\"SRF2.ch\" tvg-name=\"SRF 2\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SRF2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_4332_300C_13E_820000_0_0_0.png\" tvg-id=\"SRF2.ch\" tvg-name=\"SRF 2\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SRFzwei" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_4332_300C_13E_820000_0_0_0.png\" tvg-id=\"SRF2.ch\" tvg-name=\"SRF 2\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SRF zwei" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_4332_300C_13E_820000_0_0_0.png\" tvg-id=\"SRF2.ch\" tvg-name=\"SRF 2\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SRF info " | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_4335_300C_13E_820000_0_0_0.png\" tvg-id=\"SRFinfo.ch\" tvg-name=\"SRF Info\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SRFinfo " | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_4335_300C_13E_820000_0_0_0.png\" tvg-id=\"SRFinfo.ch\" tvg-name=\"SRF Info\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ORF 1"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/orf-1-hd.png\" tvg-id=\"ORF1.at\" tvg-name=\"ORF1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ORF1" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/orf-1-hd.png\" tvg-id=\"ORF1.at\" tvg-name=\"ORF1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ORFeins" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/orf-1-hd.png\" tvg-id=\"ORF1.at\" tvg-name=\"ORF1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ORF eins" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/orf-1-hd.png\" tvg-id=\"ORF1.at\" tvg-name=\"ORF1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ORF 2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_1330_3EF_1_C00000_0_0_0.png\" tvg-id=\"ORF2.at\" tvg-name=\"ORF2\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ORF2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_1330_3EF_1_C00000_0_0_0.png\" tvg-id=\"ORF2.at\" tvg-name=\"ORF2\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ORF 3" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_1330_3EF_1_C00000_0_0_0.png\" tvg-id=\"ORF3.at\" tvg-name=\"ORF3\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ORF3"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_33FC_3ED_1_C00000_0_0_0.png\" tvg-id=\"ORF3.at\" tvg-name=\"ORF3\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Orf III"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_33FC_3ED_1_C00000_0_0_0.png\" tvg-id=\"ORF3.at\" tvg-name=\"ORF3\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sat.1 HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_EF74_3F9_1_C00000_0_0_0.png\" tvg-id=\"Sat1.de\" tvg-name=\"Sat.1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sat.1 RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_EF74_3F9_1_C00000_0_0_0.png\" tvg-id=\"Sat1.de\" tvg-name=\"Sat.1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sat.1 FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_EF74_3F9_1_C00000_0_0_0.png\" tvg-id=\"Sat1.de\" tvg-name=\"Sat.1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sat1 HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_EF74_3F9_1_C00000_0_0_0.png\" tvg-id=\"Sat1.de\" tvg-name=\"Sat.1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sat1 FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_EF74_3F9_1_C00000_0_0_0.png\" tvg-id=\"Sat1.de\" tvg-name=\"Sat.1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sat1 RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_EF74_3F9_1_C00000_0_0_0.png\" tvg-id=\"Sat1.de\" tvg-name=\"Sat.1\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",RTL HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_D73E_227_270F_FFFF0000_0_0_0.png\" tvg-id=\"RTL.de\" tvg-name=\"RTL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",RTL FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_D73E_227_270F_FFFF0000_0_0_0.png\" tvg-id=\"RTL.de\" tvg-name=\"RTL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",RTL RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_D73E_227_270F_FFFF0000_0_0_0.png\" tvg-id=\"RTL.de\" tvg-name=\"RTL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",RTL CH HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_D73E_227_270F_FFFF0000_0_0_0.png\" tvg-id=\"RTL.de\" tvg-name=\"RTL\" group-title=\"FreeTV\",#' >> ablage.m3u 
cat index.m3u | grep -A1 -i ",RTL 2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_814E_14B_270F_FFFF0000_0_0_0.png\" tvg-id=\"RTL2.de\" tvg-name=\"RTL2\" group-title=\"FreeTV\",#' >> ablage.m3u 
cat index.m3u | grep -A1 -i ",RTL2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_814E_14B_270F_FFFF0000_0_0_0.png\" tvg-id=\"RTL2.de\" tvg-name=\"RTL2\" group-title=\"FreeTV\",#' >> ablage.m3u 
cat index.m3u | grep -A1 -i ",RTL zwei" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_814E_14B_270F_FFFF0000_0_0_0.png\" tvg-id=\"RTL2.de\" tvg-name=\"RTL2\" group-title=\"FreeTV\",#' >> ablage.m3u 
cat index.m3u | grep -A1 -i ",RTLzwei" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_814E_14B_270F_FFFF0000_0_0_0.png\" tvg-id=\"RTL2.de\" tvg-name=\"RTL2\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ProSieben HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D66_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSieben.de\" tvg-name=\"ProSieben\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ProSieben FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D66_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSieben.de\" tvg-name=\"ProSieben\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ProSieben RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D66_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSieben.de\" tvg-name=\"ProSieben\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Pro7 HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D66_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSieben.de\" tvg-name=\"ProSieben\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Pro7 FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D66_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSieben.de\" tvg-name=\"ProSieben\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Pro7 RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D66_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSieben.de\" tvg-name=\"ProSieben\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Pro 7 RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D66_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSieben.de\" tvg-name=\"ProSieben\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Pro 7 HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D66_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSieben.de\" tvg-name=\"ProSieben\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Pro 7 FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D66_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSieben.de\" tvg-name=\"ProSieben\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabel eins HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D67_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabel eins FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D67_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabel eins RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D67_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabeleins HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D67_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabeleins FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D67_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabeleins RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/halter\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabel1 HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D67_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabel1 FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D67_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabel1 RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D67_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabel 1 HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D67_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabel 1 FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D67_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabel 1 RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D67_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEins.de\" tvg-name=\"kabel eins\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Vox HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_814F_14B_270F_FFFF0000_0_0_0.png\" tvg-id=\"Vox.de\" tvg-name=\"Vox\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Vox FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_814F_14B_270F_FFFF0000_0_0_0.png\" tvg-id=\"Vox.de\" tvg-name=\"Vox\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Vox RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_814F_14B_270F_FFFF0000_0_0_0.png\" tvg-id=\"Vox.de\" tvg-name=\"Vox\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",RTL Nitro" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/rtl-nitro-hd.png\" tvg-id=\"RTLNitro.de\" tvg-name=\"RTLNitro\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",RTLNitro" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/rtl-nitro-hd.png\" tvg-id=\"RTLNitro.de\" tvg-name=\"RTLNitro\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",sixx" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_1_4E94_A1_270F_FFFF0000_0_0_0.png\" tvg-id=\"Sixx.de\" tvg-name=\"sixx\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DMAX" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7980_1C3_270F_FFFF0000_0_0_0.png\" tvg-id=\"DMax.de\" tvg-name=\"DMAX\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",PHOENIX" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_2F53_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"phoenix.de\" tvg-name=\"PHOENIX\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ServusTV" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_71B5_191_270F_FFFF0000_0_0_0.png\" tvg-id=\"ServusTV.at\" tvg-name=\"ServusTV\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Servus TV" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_71B5_191_270F_FFFF0000_0_0_0.png\" tvg-id=\"ServusTV.at\" tvg-name=\"ServusTV\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ZDF:neo" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_A08F_191_270F_FFFF0000_0_0_0.png\" tvg-id=\"ZDFneo.de\" tvg-name=\"ZDFneo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ZDFneo" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_A08F_191_270F_FFFF0000_0_0_0.png\" tvg-id=\"ZDFneo.de\" tvg-name=\"ZDFneo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ZDF neo" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_A08F_191_270F_FFFF0000_0_0_0.png\" tvg-id=\"ZDFneo.de\" tvg-name=\"ZDFneo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ZDF_neo" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_A08F_191_270F_FFFF0000_0_0_0.png\" tvg-id=\"ZDFneo.de\" tvg-name=\"ZDFneo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ZDFinfo" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_A85E_1AF_270F_FFFF0000_0_0_0.png\" tvg-id=\"ZDFinfo.de\" tvg-name=\"ZDFinfo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ZDF info" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_A85E_1AF_270F_FFFF0000_0_0_0.png\" tvg-id=\"ZDFinfo.de\" tvg-name=\"ZDFinfo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",arte" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_42D9_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"ARTE.de\" tvg-name=\"arte\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",3sat" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_A08D_19B_270F_FFFF0000_0_0_0.png\" tvg-id=\"3sat.de\" tvg-name=\"3sat\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Heimatkanal" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/heimat-kanal.png\" tvg-id=\"Heimatkanal.de\" tvg-name=\"3sat\" group-title=\"FreeTV\",#' >> ablage.m3u 
	
	cat index.m3u | grep -A1 -i ",MDR HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/mdr-hd.png\" tvg-id=\"MDRS-Anhalt.de\" tvg-name=\"MDR\" group-title=\"FreeTV\",#' >> ablage.m3u 	
	
	
	
	

	
	
	cat index.m3u | grep -A1 -i ",Sky Cinema Premieren HD"| sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_83_6_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCinemaPremieren.de\" tvg-name=\"Sky Cinema Premieren\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Cinema Premieren FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_83_6_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCinemaPremieren.de\" tvg-name=\"Sky Cinema Premieren\" group-title=\"FreeTV\",#' >> ablage.m3u 
	#cat index.m3u | grep -A1 -i ",Sky Cinema Premieren RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_83_6_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCinemaPremieren.de\" tvg-name=\"Sky Cinema Premieren\" group-title=\"FreeTV\",#' >> ablage.m3u 
	#cat index.m3u | grep -A1 -i ",Sky Cinema HD"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_83_6_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCinemaPremieren.de\" tvg-name=\"Sky Cinema Premieren\" group-title=\"FreeTV\",#' >> ablage.m3u 
	#cat index.m3u | grep -A1 -i ",Sky Cinema FHD"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_83_6_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCinemaPremieren.de\" tvg-name=\"Sky Cinema Premieren\" group-title=\"FreeTV\",#' >> ablage.m3u
	cat index.m3u | grep -A1 -i ",SKY CINEMA PREMIERE HD"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_83_6_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCinemaPremieren.de\" tvg-name=\"Sky Cinema Premieren\" group-title=\"FreeTV\",#' >> ablage.m3u
	cat index.m3u | grep -A1 -i ",SKY CINEMA PREMIERE FHD"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_83_6_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCinemaPremieren.de\" tvg-name=\"Sky Cinema Premieren\" group-title=\"FreeTV\",#' >> ablage.m3u
	#cat index.m3u | grep -A1 -i ",Sky Cinema RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_83_6_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCinema.de\" tvg-name=\"Sky Cinema Premieren\" group-title=\"FreeTV\",#' >> ablage.m3u 
	#cat index.m3u | grep -A1 -i ",Sky Cinema Premieren +24" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky24.png\" tvg-id=\"SkyCinemaPlus24.de\" tvg-name=\"Sky Cinema Premieren +24\" group-title=\"FreeTV\",#' >> ablage.m3u 
	#cat index.m3u | grep -A1 -i ",Sky Cinema Premieren+24" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky24.png\" tvg-id=\"SkyCinemaPlus24.de\" tvg-name=\"Sky Cinema Premieren +24\" group-title=\"FreeTV\",#' >> ablage.m3u 
	#cat index.m3u | grep -A1 -i ",Sky Cinema +24" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky24.png\" tvg-id=\"SkyCinemaPlus24.de\" tvg-name=\"Sky Cinema Premieren +24\" group-title=\"FreeTV\",#' >> ablage.m3u 
	#cat index.m3u | grep -A1 -i ",Sky Cinema+24" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky24.png\" tvg-id=\"SkyCinemaPlus24.de\" tvg-name=\"Sky Cinema Premieren +24\" group-title=\"FreeTV\",#' >> ablage.m3u 
	#cat index.m3u | grep -A1 -i ",Sky Cinema Best Of" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_6B_D_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCinemaHits.de\" tvg-name=\"Sky Cinema Best Of\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Cinema Action" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_74_D_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyAction.de\" tvg-name=\"Sky Cinema Action\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SKY CINEMA ACTION HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_74_D_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyAction.de\" tvg-name=\"Sky Cinema Action\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SKY CINEMA ACTION FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_74_D_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyAction.de\" tvg-name=\"Sky Cinema Action\" group-title=\"FreeTV\",#' >> ablage.m3u 
	#cat index.m3u | grep -A1 -i ",Sky Cinema Special" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_6F_D_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCinemaSpecial.de\" tvg-name=\"Sky Cinema Spezial\" group-title=\"FreeTV\",#' >> ablage.m3u 
	#cat index.m3u | grep -A1 -i ",Sky Cinema Thriller" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_B_C_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCinemaThriller.de\" tvg-name=\"Sky Cinema Thriller\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Cinema Family" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-cinema-family-hd.png\" tvg-id=\"SkyCinemaFamily.de\" tvg-name=\"Sky Cinema Family\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SKY CINEMA FAMILY FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-cinema-family-hd.png\" tvg-id=\"SkyCinemaFamily.de\" tvg-name=\"Sky Cinema Family\" group-title=\"FreeTV\",#' >> ablage.m3u
		cat index.m3u | grep -A1 -i ",SKY CINEMA HIGHLIGHTS" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_006E_0085_000D_00C00000_0_0_0_0.png\" tvg-id=\"SkyCinemaHighlights.de\" tvg-name=\"Sky Cinema Highlights\" group-title=\"FreeTV\",#' >> ablage.m3u 
	
	cat index.m3u | grep -A1 -i ",SKY HIGHLIGHTS" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_006E_0085_000D_00C00000_0_0_0_0.png\" tvg-id=\"SkyCinemaHighlights.de\" tvg-name=\"Sky Cinema Highlights\" group-title=\"FreeTV\",#' >> ablage.m3u 	

	cat index.m3u | grep -A1 -i ",Sky Krimi" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_17_1_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyKrimi.de\" tvg-name=\"Sky Krimi\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SKY KRIMI" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_17_1_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyKrimi.de\" tvg-name=\"Sky Krimi\" group-title=\"FreeTV\",#' >> ablage.m3u
	cat index.m3u | grep -A1 -i ",Sky Atlantic"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_6E_D_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyAtlanticHD.de\" tvg-name=\"Sky Atlantic\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SKY CINEMA ATLANTIC HD"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://sltv-logo.cms-s.com/logo/germanynew/sky_atlantic.png\" tvg-id=\"SkyAtlanticHD.de\" tvg-name=\"Sky Atlantic\" group-title=\"FreeTV\",#' >> ablage.m3u
	cat index.m3u | grep -A1 -i ",SKY CINEMA ATLANTIC FHD"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://sltv-logo.cms-s.com/logo/germanynew/sky_atlantic.png\" tvg-id=\"SkyAtlanticHD.de\" tvg-name=\"Sky Atlantic\" group-title=\"FreeTV\",#' >> ablage.m3u
	cat index.m3u | grep -A1 -i ",Sky 1" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/halter\" tvg-id=\"Sky1.de\" tvg-name=\"Sky One\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky One" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_93_D_85_FFFF0000_0_0_0.png\" tvg-id=\"Sky1.de\" tvg-name=\"Sky One\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SKY ONE FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_93_D_85_FFFF0000_0_0_0.png\" tvg-id=\"Sky1.de\" tvg-name=\"Sky One\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Replay" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-replay-hd.png\" tvg-id=\"SkyReplay.de\" tvg-name=\"Sky Replay\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Comedy" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_E_3_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyComedy.de\" tvg-name=\"Sky Comedy\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Crime" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_D_3_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCrime.de\" tvg-name=\"Sky Crime\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SKY CRIME FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_D_3_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyCrime.de\" tvg-name=\"Sky Crime\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Cinema Classics" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-cinema-classics-hd.png\" tvg-id=\"SkyCinemaClassics.de\" tvg-name=\"Sky Cinema Classics\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SKY CINEMA CLASSICS FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-cinema-classics-hd.png\" tvg-id=\"SkyCinemaClassics.de\" tvg-name=\"Sky Cinema Classics\" group-title=\"FreeTV\",#' >> ablage.m3u 
	
	
	
	

	
	cat index.m3u | grep -A1 -i ",SKY SHOWCASE" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://sltv-logo.cms-s.com/logo/germanynew/skyShowase.png\" tvg-id=\"SkyShowcase.de\" tvg-name=\"Sky Cinema Highlights HD\" group-title=\"FreeTV\",#' >> ablage.m3u 
	

	
	cat index.m3u | grep -A1 -i ",Romance TV" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_797F_1AF_270F_FFFF0000_0_0_0.png\" tvg-id=\"Romance.de\" tvg-name=\"RomanceTV\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SYFY" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69EA_19B_270F_FFFF0000_0_0_0.png\" tvg-id=\"SciFi.de\" tvg-name=\"SYFY\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SKY SYFY FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://sltv-logo.cms-s.com/logo/germanynew/sky_syfy.png\" tvg-id=\"SciFi.de\" tvg-name=\"SYFY\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",13th Street" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_6219_19B_270F_FFFF0000_0_0_0.png\" tvg-id=\"13thStreet.de\" tvg-name=\"13th Street\" group-title=\"FreeTV\",#' >> ablage.m3u 
	#cat index.m3u | grep -A1 -i ",SONY AXN" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_9CA5_191_270F_FFFF0000_0_0_0.png\" tvg-id=\"AXN.de\" tvg-name=\"SONY AXN\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",AXN BLACK" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://sltv-logo.cms-s.com/logo/germanynew/AXN_BLACK.png\" tvg-id=\"AXNBlack.de\" tvg-name=\"AXN Black\" group-title=\"FreeTV\",#' >> ablage.m3u
	cat index.m3u | grep -A1 -i ",AXN WHITE" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://sltv-logo.cms-s.com/logo/germanynew/AXN_BLACK.png\" tvg-id=\"AXNWhite.de\" tvg-name=\"AXN White\" group-title=\"FreeTV\",#' >> ablage.m3u
	cat index.m3u | grep -A1 -i ",Universal TV" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_2B92_6F_270F_FFFF0000_0_0_0.png\" tvg-id=\"Universal.de\" tvg-name=\"UniversalTV\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Warner TV Film" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_5274_19B_270F_FFFF0000_0_0_0.png\" tvg-id=\"WarnerTVFilm.de\" tvg-name=\"Warner TV Film\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Warner Film" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_5274_19B_270F_FFFF0000_0_0_0.png\" tvg-id=\"WarnerTVFilm.de\" tvg-name=\"Warner TV Film\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",TNT Film" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_5274_19B_270F_FFFF0000_0_0_0.png\" tvg-id=\"WarnerTVFilm.de\" tvg-name=\"Warner TV Film\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Warner TV Serie" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_DB2B_231_270F_FFFF0000_0_0_0.png\" tvg-id=\"WarnerTVSerie.de\" tvg-name=\"Warner TV Serie\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Warner Serie" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_DB2B_231_270F_FFFF0000_0_0_0.png\" tvg-id=\"WarnerTVSerie.de\" tvg-name=\"Warner TV Serie\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",TNT Serie" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_DB2B_231_270F_FFFF0000_0_0_0.png\" tvg-id=\"WarnerTVSerie.de\" tvg-name=\"Warner TV Serie\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Warner TV Comedy" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_94D6_1AF_270F_FFFF0000_0_0_0.png\" tvg-id=\"WarnerTVComedy.de\" tvg-name=\"Warner TV Comedy\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Warner Comedy" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_94D6_1AF_270F_FFFF0000_0_0_0.png\" tvg-id=\"WarnerTVComedy.de\" tvg-name=\"Warner TV Comedy\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",TNT Comedy" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_94D6_1AF_270F_FFFF0000_0_0_0.png\" tvg-id=\"WarnerTVComedy.de\" tvg-name=\"Warner TV Comedy\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",KABEL 1 CLASSICS" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_98BD_187_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEinsClassic.de\" tvg-name=\"kabeleinsclassics\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabeleinsclassics" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_98BD_187_270F_FFFF0000_0_0_0.png\" tvg-id=\"KabelEinsClassic.de\" tvg-name=\"kabeleinsclassics\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",KINOWELT TV" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_75A4_1A5_270F_FFFF0000_0_0_0.png\" tvg-id=\"Kinowelt.de\" tvg-name=\"KINOWELT TV\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Silverline" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_1_E2FD_245_270F_FFFF0000_0_0_0.png\" tvg-id=\"Silverline.de\" tvg-name=\"Silverline Movie Channel\" group-title=\"FreeTV\",#' >> ablage.m3u 
	
	
	
	
	cat index.m3u | grep -A1 -i ",Anixe" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_526C_41D_1_C00000_0_0_0.png\" tvg-id=\"Anixe.de\" tvg-name=\"Anixe\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Pro7 MAXX" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D69_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSiebenMaxx.de\" tvg-name=\"ProSiebenMaxx\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ProSieben MAXX" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D69_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSiebenMaxx.de\" tvg-name=\"ProSiebenMaxx\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ProSiebenMaxx" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D69_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSiebenMaxx.de\" tvg-name=\"ProSiebenMaxx\" group-title=\"FreeTV\",#' >> ablage.m3u

	cat index.m3u | grep -A1 -i ",RTL Crime" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_94D7_14B_270F_FFFF0000_0_0_0.png\" tvg-id=\"RTLCrime.de\" tvg-name=\"RTL Crime\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ProSieben Fun" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_94D5_187_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSiebenFun.de\" tvg-name=\"ProSieben Fun\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Pro7 Fun" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_94D5_187_270F_FFFF0000_0_0_0.png\" tvg-id=\"ProSiebenFun.de\" tvg-name=\"ProSieben Fun\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",RTL Living" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_B415_187_270F_FFFF0000_0_0_0.png\" tvg-id=\"RTLLiving.de\" tvg-name=\"RTL Living\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",RTL PASSION" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/rtl-passion-hd.png\" tvg-id=\"RTLPassion.de\" tvg-name=\"RTL Passion\" group-title=\"FreeTV\",#' >> ablage.m3u
	

	
	
	
	
	cat index.m3u | grep -A1 -i ",TLC" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_C3B5_6F_270F_FFFF0000_0_0_0.png\" tvg-id=\"TLC.de\" tvg-name=\"TLC\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Tele 5" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_9CA6_6F_270F_FFFF0000_0_0_0.png\" tvg-id=\"Tele5.de\" tvg-name=\"Tele 5\" group-title=\"FreeTV\",#' >> ablage.m3u 
	
	cat index.m3u | grep -A1 -i ",VOXup" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_1_566E_DD_270F_FFFF0000_0_0_0.png\" tvg-id=\"VOXup.de\" tvg-name=\"VOXup\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",VOX up" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_1_566E_DD_270F_FFFF0000_0_0_0.png\" tvg-id=\"VOXup.de\" tvg-name=\"VOXup\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",RTLup" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_AC4D_1B9_270F_FFFF0000_0_0_0.png\" tvg-id=\"RTLPlus.de\" tvg-name=\"RTLup\" group-title=\"FreeTV\",#' >> ablage.m3u 

	cat index.m3u | grep -A1 -i ",Discovery" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_E2F5_245_270F_FFFF0000_0_0_0.png\" tvg-id=\"DiscoveryChannel.de\" tvg-name=\"Discovery\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",NatGeo HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D6C_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"NatGeoHD.de\" tvg-name=\"NatGeo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",NatGeo FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D6C_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"NatGeoHD.de\" tvg-name=\"NatGeo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",NatGeo RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D6C_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"NatGeoHD.de\" tvg-name=\"NatGeo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",National Geographic HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D6C_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"NatGeoHD.de\" tvg-name=\"NatGeo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",National Geographic FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D6C_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"NatGeoHD.de\" tvg-name=\"NatGeo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",National Geographic RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_7D6C_141_270F_FFFF0000_0_0_0.png\" tvg-id=\"NatGeoHD.de\" tvg-name=\"NatGeo\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Nat Geo Wild" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_A475_1A5_270F_FFFF0000_0_0_0.png\" tvg-id=\"NatGeoWild.de\" tvg-name=\"NatGeoWild\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",National Geographic Wild" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_A475_1A5_270F_FFFF0000_0_0_0.png\" tvg-id=\"NatGeoWild.de\" tvg-name=\"NatGeoWild\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",HISTORY" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_E2F6_245_270F_FFFF0000_0_0_0.png\" tvg-id=\"HistoryHD.de\" tvg-name=\"HISTORY\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Spiegel Geschichte" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_89_10_85_C00000_0_0_0.png\" tvg-id=\"SpiegelGeschichte.de\" tvg-name=\"Spiegel Geschichte\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Spiegel TV Wissen" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_621B_1B9_270F_FFFF0000_0_0_0.png\" tvg-id=\"CuriosityChannel.de\" tvg-name=\"Curiosity Channel\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Curiosity Channel HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_621B_1B9_270F_FFFF0000_0_0_0.png\" tvg-id=\"CuriosityChannel.de\" tvg-name=\"Curiosity Channel\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Documentaries" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_10_4_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyDocumentaries.de\" tvg-name=\"Sky Documentaries\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Nature" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_F_4_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyNature.de\" tvg-name=\"Sky Nature\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Animal Planet" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_4DA_C_1_FFFF0000_0_0_0.png\" tvg-id=\"AnimalPlanet.de\" tvg-name=\"Animal Planet\" group-title=\"FreeTV\",#' >> ablage.m3u 
	
	
	
	
	cat index.m3u | grep -A1 -i ",kabel eins Doku" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/kabel1-doku-hd.png\" tvg-id=\"KabelEinsDoku.de\" tvg-name=\"kabel eins Doku\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",kabel 1 Doku" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/kabel1-doku-hd.png\" tvg-id=\"KabelEinsDoku.de\" tvg-name=\"kabel eins Doku\" group-title=\"FreeTV\",#' >> ablage.m3u 
	
	

	
#	cat index.m3u | grep -A1 -i ",BILD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_8154_14B_270F_FFFF0000_0_0_0.png\" tvg-id=\"BILD.de\" tvg-name=\"BILD\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Welt HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_C79D_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"WELT.de\" tvg-name=\"Welt\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Welt FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_C79D_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"WELT.de\" tvg-name=\"Welt\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Welt RAW"| sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_C79D_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"WELT.de\" tvg-name=\"Welt\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",NTV" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_C79E_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"ntv.de\" tvg-name=\"NTV\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",N-TV" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_C79E_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"ntv.de\" tvg-name=\"NTV\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Comedy Central" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_B02D_1C3_270F_FFFF0000_0_0_0.png\" tvg-id=\"ComedyCentralVIVA.de\" tvg-name=\"Comedy Central\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Kika HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_2B91_6F_270F_FFFF0000_0_0_0.png\" tvg-id=\"Kika.de\" tvg-name=\"Kika\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Super RTL HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_8150_14B_270F_FFFF0000_0_0_0.png\" tvg-id=\"SuperRTL.de\" tvg-name=\"Super RTL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DISNEY CHANNEL HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69E7_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"disneychannel.de\" tvg-name=\"DISNEY CHANNEL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DISNEY CHANNEL FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69E7_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"disneychannel.de\" tvg-name=\"DISNEY CHANNEL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DISNEY CHANNEL RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69E7_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"disneychannel.de\" tvg-name=\"DISNEY CHANNEL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DISNEY HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69E7_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"disneychannel.de\" tvg-name=\"DISNEY CHANNEL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DISNEY FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69E7_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"disneychannel.de\" tvg-name=\"DISNEY CHANNEL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DISNEY RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69E7_79_270F_FFFF0000_0_0_0.png\" tvg-id=\"disneychannel.de\" tvg-name=\"DISNEY CHANNEL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	
	
	cat index.m3u | grep -A1 -i ",CARTOON NETWORK" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/cartoon-network-hd.png\" tvg-id=\"CartoonNetwork.de\" tvg-name=\"DISNEY CHANNEL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	
	cat index.m3u | grep -A1 -i ",BOOMERANG" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/boomerang-hd.png\" tvg-id=\"Boomerang.de\" tvg-name=\"DISNEY CHANNEL\" group-title=\"FreeTV\",#' >> ablage.m3u 
	
	
	

	
	
	
	cat index.m3u | grep -A1 -i ",nick/MTV+" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_9CA7_6F_270F_FFFF0000_0_0_0.png\" tvg-id=\"Nickelodeon.de\" tvg-name=\"nick/MTV+\" group-title=\"FreeTV\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DELUXE MUSIC" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_B417_1C3_270F_FFFF0000_0_0_0.png\" tvg-id=\"DeLuxeMusic.de\" tvg-name=\"DELUXE MUSIC\" group-title=\"FreeTV\",#' >> ablage.m3u 

cat index.m3u | grep -A1 -i ",MotorVision"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_16_A8_B_85_C00000_0_0_0.png\" tvg-id=\"MotorVision.de\" tvg-name=\"MotorVision\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ORF Sport" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_33FD_3ED_1_C00000_0_0_0.png\" tvg-id=\"ORFSport.at\" tvg-name=\"ORF Sport\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",ORFSport" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_33FD_3ED_1_C00000_0_0_0.png\" tvg-id=\"ORFSport.at\" tvg-name=\"ORF Sport\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sport1 HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_4E96_19B_270F_FFFF0000_0_0_0.png\" tvg-id=\"Sport1HD.de\" tvg-name=\"Sport1\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sport1+ HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sport1+hd.png\" tvg-id=\"SPORT1plus.de\" tvg-name=\"Sport1\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Eurosport 1" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_DB28_231_270F_FFFF0000_0_0_0.png\" tvg-id=\"Eurosport1.de\" tvg-name=\"Eurosport1\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Eurosport1" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_DB28_231_270F_FFFF0000_0_0_0.png\" tvg-id=\"Eurosport1.de\" tvg-name=\"Eurosport1\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Eurosport 2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_B030_1C3_270F_FFFF0000_0_0_0.png\" tvg-id=\"Eurosport2.de\" tvg-name=\"Eurosport2\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Eurosport2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_B030_1C3_270F_FFFF0000_0_0_0.png\" tvg-id=\"Eurosport2.de\" tvg-name=\"Eurosport2\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DAZN 1 HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/dazn1.png\" tvg-id=\"DAZN1.de\" tvg-name=\"DAZN1\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DAZN1 HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/dazn1.png\" tvg-id=\"DAZN1.de\" tvg-name=\"DAZN1\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DAZN 2 HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/dazn2.png\" tvg-id=\"DAZN2.de\" tvg-name=\"DAZN2\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",DAZN2 HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/dazn2.png\" tvg-id=\"DAZN2.de\" tvg-name=\"DAZN2\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Premier League" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/2-sky-sports-league-1.png\" tvg-id=\"SkySportPremierLeague.de\" tvg-name=\"Sky Premier League\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport F1" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_11_4_85_FFFF0000_0_0_0.png\" tvg-id=\"SkySportF1.de\" tvg-name=\"Sky Sport F1\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Tennis" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/skytennis.png\" tvg-id=\"SkySportTennis.de\" tvg-name=\"Sky Sport Tennis\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Golf" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/2-sky-sports-golf.png\" tvg-id=\"SkySportGolf.de\" tvg-name=\"Sky Sport Golf\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Mix" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/2-sky-sports-mix.png\" tvg-id=\"SkySportMix.de\" tvg-name=\"Sky Sport Mix\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Top Event" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/skytopevent.png\" tvg-id=\"SkySportTopEvent.de\" tvg-name=\"Sky Sport Top Event\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport 1" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport1-hd.png\" tvg-id=\"SkySport1.de\" tvg-name=\"Sky Sport 1\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport 2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport2-hd.png\" tvg-id=\"SkySport2.de\" tvg-name=\"Sky Sport 2\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport 3" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport3-hd.png\" tvg-id=\"SkySport3sat.de\" tvg-name=\"Sky Sport 3\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport 4" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport4-hd.png\" tvg-id=\"SkySport4.de\" tvg-name=\"Sky Sport 4\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport 5" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport5-hd.png\" tvg-id=\"SkySport5.de\" tvg-name=\"Sky Sport 5\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport 6" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport6-hd.png\" tvg-id=\"SkySport6.de\" tvg-name=\"Sky Sport 6\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69_C_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyBundesliga.de\" tvg-name=\"Sky Sport Bundesliga HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69_C_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyBundesliga.de\" tvg-name=\"Sky Sport Bundesliga HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga RAW"| sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69_C_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyBundesliga.de\" tvg-name=\"Sky Sport Bundesliga HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69_C_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyBundesliga.de\" tvg-name=\"Sky Sport Bundesliga HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga FHD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69_C_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyBundesliga.de\" tvg-name=\"Sky Sport Bundesliga HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga RAW" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69_C_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyBundesliga.de\" tvg-name=\"Sky Sport Bundesliga HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga 1" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_69_C_85_FFFF0000_0_0_0.png\" tvg-id=\"SkyBundesliga1.de\" tvg-name=\"Sky Sport Bundesliga 1 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga 1" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl1-hd.png\" tvg-id=\"SkyBundesliga1.de\" tvg-name=\"Sky Sport Bundesliga 1 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga 2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl2-hd.png\" tvg-id=\"SkyBundesliga2.de\" tvg-name=\"Sky Sport Bundesliga 2 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga 2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl2-hd.png\" tvg-id=\"SkyBundesliga2.de\" tvg-name=\"Sky Sport Bundesliga 2 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga 3" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl3-hd.png\" tvg-id=\"SkyBundesliga3sat.de\" tvg-name=\"Sky Sport Bundesliga 3 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga 3" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl3-hd.png\" tvg-id=\"SkyBundesliga3sat.de\" tvg-name=\"Sky Sport Bundesliga 3 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga 4" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl4-hd.png\" tvg-id=\"SkyBundesliga4.de\" tvg-name=\"Sky Sport Bundesliga 4 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga 4" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl4-hd.png\" tvg-id=\"SkyBundesliga4.de\" tvg-name=\"Sky Sport Bundesliga 4 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga 5" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl5-hd.png\" tvg-id=\"SkyBundesliga5.de\" tvg-name=\"Sky Sport Bundesliga 5 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga 5" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl5-hd.png\" tvg-id=\"SkyBundesliga5.de\" tvg-name=\"Sky Sport Bundesliga 5 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga 6"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl6-hd.png\" tvg-id=\"SkyBundesliga6.de\" tvg-name=\"Sky Sport Bundesliga 6 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga 6"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl6-hd.png\" tvg-id=\"SkyBundesliga6.de\" tvg-name=\"Sky Sport Bundesliga 6 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga 7" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl7-hd.png\" tvg-id=\"SkyBundesliga7.de\" tvg-name=\"Sky Sport Bundesliga 7 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga 7" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl7-hd.png\" tvg-id=\"SkyBundesliga7.de\" tvg-name=\"Sky Sport Bundesliga 7 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga 8" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl8-hd.png\" tvg-id=\"SkyBundesliga8.de\" tvg-name=\"Sky Sport Bundesliga 8 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga 8" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl8-hd.png\" tvg-id=\"SkyBundesliga8.de\" tvg-name=\"Sky Sport Bundesliga 8 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Bundesliga 9" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl9-hd.png\" tvg-id=\"SkyBundesliga9.de\" tvg-name=\"Sky Sport Bundesliga 9 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Bundesliga 9" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/sky-sport-bl9-hd.png\" tvg-id=\"SkyBundesliga9.de\" tvg-name=\"Sky Sport Bundesliga 9 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Austria HD" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_8F_8_85_C00000_0_0_0.png\" tvg-id=\"SkySportAustria.de\" tvg-name=\"Sky Sport Austria HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Austria 1" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_8F_8_85_C00000_0_0_0.png\" tvg-id=\"SkySportAustria.de\" tvg-name=\"Sky Sport Austria 1 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Austria 2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_149_8_85_C00000_0_0_0.png\" tvg-id=\"SkySportAustria2.at\" tvg-name=\"Sky Sport Austria 2 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport Austria 3" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_153_8_85_C00000_0_0_0.png\" tvg-id=\"SkySportAustria3.at\" tvg-name=\"Sky Sport Austria 3 HD\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",Sky Sport News"  | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_6C_C_85_FFFF0000_0_0_0.png\" tvg-id=\"SkySportNewsHD.de\" tvg-name=\"Sky Sport News\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	cat index.m3u | grep -A1 -i ",SPORTDIGITAL FUSSBALL" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/1_0_19_9CA8_191_270F_FFFF0000_0_0_0.png\" tvg-id=\"sportdigital.de\" tvg-name=\"SPORTDIGITAL FUSSBALL\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
	
		cat index.m3u | grep -A1 -i ",Blue Sport 1" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/blue-sport1-hd.png\" tvg-id=\"blueSport1.ch\" tvg-name=\"SPORTDIGITAL FUSSBALL\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 
		
		cat index.m3u | grep -A1 -i ",Blue Sport 2" | sed 's#\#EXTINF#halter1 halter2#g' | sed 's/halter2.*,//' | sed 's#halter1#\#EXTINF:-1 tvg-logo=\"http://jinxx.mooo.com/picon/blue-sport2-hd.png\" tvg-id=\"blueSport2.ch\" tvg-name=\"SPORTDIGITAL FUSSBALL\" group-title=\"FreeTV Sport\",#' >> ablage.m3u 	
		

 	
 	
 	
 	
 	



	cat ablage.m3u | sed 's#, #,#g' | sed '/^#EXTINF/a#EXTVLCOPT:http-user-agent=VAVOO/2.6' > ablage2.m3u
	sed '/--/d' ablage2.m3u  > $ausgabe.m3u
	
rm ablage*
rm index*
exit 0

	
